# Generated by Django 5.2.9 on 2026-01-13 02:39

import comment_app.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[comment_app.validators.validate_id]), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
